name: Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v3
      with:
        node-version: 18.17.1
    - name: Install dependencies
      run: npm install -f --no-audit --no-fund --no-optional
    - name: Create .env file
      run: |
        echo "DATABASE_URI=${{ secrets.DATABASE_URI }}" > .env
        echo "STRIPE_SK=${{ secrets.STRIPE_SK }}" >> .env
        echo "SECRET=${{ secrets.SECRET }}" >> .env
        echo "PORT=${{ secrets.PORT }}" >> .env
        echo "PUBLIC_API_URL=${{ secrets.PUBLIC_API_URL }}" >> .env
        echo "PUBLIC_UPLOADS_URL=${{ secrets.PUBLIC_UPLOADS_URL }}" >> .env
    - name: Run build task
      run: |
        npm run build
    - name: Deploy to DO Server
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        ARGS: "-rltgoDzvO"
        SOURCE: "./"
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET: /home/${{ secrets.REMOTE_USER }}/${{ secrets.REMOTE_HOST }}
        EXCLUDE: "/node_modules/"
    - name: Npm install & restart
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/${{ secrets.REMOTE_USER }}/${{ secrets.REMOTE_HOST }}
          npm install
          pm2 reload "server"
